SELECT BRANCHID FROM BRANCH 
WHERE EXISTS (SELECT BRANCHID FROM CAR WHERE BRANCHID = BRANCH.BRANCHID)


INSERT INTO CAR
VALUES
(10,'volkswagen passat',2020,'pink',55000,'hetchback','germany',false,4);
SELECT * FROM CAR

SELECT COLOR ,
CASE WHEN COLOR ='red'THEN 'red color'
WHEN COLOR ='black' THEN 'black color'
ELSE 'other colors'
	END
FROM CAR;

EXPLAIN SELECT * FROM CAR

EXPLAIN ANALYZE SELECT * FROM CAR
