SELECT DISTINCT *  FROM CAR
WHERE COLOR IN ('red','green') AND CARPRICE BETWEEN 10000 AND 4000000
ORDER BY carprice DESC

SELECT * FROM CAR
WHERE CARPRICE >(SELECT AVG(CARPRICE)FROM CAR)

SELECT * ,
(SELECT personaldataid FROM EMPLOYEE WHERE EMPLOYEE.EMPLOYEEID = PURCHASEORDER.EMPLOYEEID)
FROM PURCHASEORDER;


SELECT * FROM PURCHASEORDER, EMPLOYEE, personaldata
WHERE PURCHASEORDER.EMPLOYEEID = EMPLOYEE.EMPLOYEEID AND EMPLOYEE.PERSONALDATAID = PERSONALDATA.PERSONALDATAID